#! /usr/bin/env python3

'''
Zero free blocks from VDI filesystem and compact it
'''

import sys
import os
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
import subprocess
import shlex


def main():
    '''
    Run
    '''

    parser = ArgumentParser(description=__doc__,
                            formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument('vdi')
    parser.add_argument('-d', '--device', default='/dev/nbd0',
                        help="network block device")
    args = parser.parse_args()

    vdipath = os.path.expanduser(args.vdi)
    try:
        subprocess.check_call(['sudo', 'qemu-nbd', '-c', args.device, vdipath])
        subprocess.check_call(['sudo', 'zerofree', '-v', '%sp1' % args.device])
        subprocess.check_call(['sudo', 'qemu-nbd', '-d', args.device])
        subprocess.check_call(['VBoxManage',
                               'modifymedium',
                               vdipath,
                               '--compact'])
    except subprocess.CalledProcessError as exc:
        cmd = ' '.join([shlex.quote(arg) for arg in exc.cmd])
        print("Couldn't run %s" % cmd)


if __name__ == '__main__':
    sys.exit(main())
